#!/usr/bin/env php
<?php
/**
 * Coverage Threshold Checker
 * 
 * Enforces minimum code coverage thresholds for the project.
 * This script reads the coverage/clover.xml file generated by PHPUnit
 * and verifies that coverage meets or exceeds the defined thresholds.
 * 
 * Usage: php scripts/check-coverage.php
 * 
 * Exit codes:
 * - 0: Coverage meets all thresholds
 * - 1: Coverage below thresholds or error occurred
 */

declare(strict_types=1);

// Define minimum coverage thresholds (percentage)
const MIN_LINE_COVERAGE = 70.0;
const MIN_METHOD_COVERAGE = 70.0;
const MIN_CLASS_COVERAGE = 70.0;

// ANSI color codes for output
const COLOR_RED = "\033[31m";
const COLOR_GREEN = "\033[32m";
const COLOR_YELLOW = "\033[33m";
const COLOR_BLUE = "\033[34m";
const COLOR_RESET = "\033[0m";
const COLOR_BOLD = "\033[1m";

/**
 * Main execution function
 */
function main(): int
{
    echo COLOR_BOLD . "=================================================\n" . COLOR_RESET;
    echo COLOR_BOLD . "  Code Coverage Threshold Checker\n" . COLOR_RESET;
    echo COLOR_BOLD . "=================================================\n\n" . COLOR_RESET;

    // Locate clover.xml file
    $cloverPath = __DIR__ . '/../coverage/clover.xml';
    
    if (!file_exists($cloverPath)) {
        echo COLOR_RED . "❌ Error: Coverage report not found at: $cloverPath\n" . COLOR_RESET;
        echo COLOR_YELLOW . "\nℹ️  Run coverage tests first:\n" . COLOR_RESET;
        echo "   composer test-coverage\n\n";
        return 1;
    }

    // Parse the coverage report
    $coverage = parseCoverageReport($cloverPath);
    
    if ($coverage === null) {
        echo COLOR_RED . "❌ Error: Failed to parse coverage report\n" . COLOR_RESET;
        return 1;
    }

    // Display coverage results
    displayCoverageResults($coverage);

    // Check thresholds
    $passed = checkThresholds($coverage);

    echo "\n" . COLOR_BOLD . "=================================================\n" . COLOR_RESET;
    
    if ($passed) {
        echo COLOR_GREEN . COLOR_BOLD . "✓ All coverage thresholds met!\n" . COLOR_RESET;
        echo COLOR_BOLD . "=================================================\n\n" . COLOR_RESET;
        return 0;
    } else {
        echo COLOR_RED . COLOR_BOLD . "✗ Coverage below minimum thresholds\n" . COLOR_RESET;
        echo COLOR_BOLD . "=================================================\n\n" . COLOR_RESET;
        echo COLOR_YELLOW . "Please improve test coverage to meet the minimum thresholds.\n" . COLOR_RESET;
        echo "View detailed coverage report: coverage/html/index.html\n\n";
        return 1;
    }
}

/**
 * Parse the Clover XML coverage report
 * 
 * @param string $path Path to clover.xml
 * @return array|null Coverage metrics or null on error
 */
function parseCoverageReport(string $path): ?array
{
    try {
        $xml = simplexml_load_file($path);
        
        if ($xml === false) {
            return null;
        }

        // Get project-level metrics
        $metrics = $xml->project->metrics;
        
        if (!$metrics) {
            return null;
        }

        // Calculate coverage percentages
        $elements = (int)$metrics['elements'];
        $coveredElements = (int)$metrics['coveredelements'];
        $statements = (int)$metrics['statements'];
        $coveredStatements = (int)$metrics['coveredstatements'];
        $methods = (int)$metrics['methods'];
        $coveredMethods = (int)$metrics['coveredmethods'];
        $classes = (int)$metrics['classes'];
        $coveredClasses = (int)$metrics['coveredclasses'];

        return [
            'line' => [
                'total' => $statements,
                'covered' => $coveredStatements,
                'percentage' => $statements > 0 ? ($coveredStatements / $statements) * 100 : 0
            ],
            'method' => [
                'total' => $methods,
                'covered' => $coveredMethods,
                'percentage' => $methods > 0 ? ($coveredMethods / $methods) * 100 : 0
            ],
            'class' => [
                'total' => $classes,
                'covered' => $coveredClasses,
                'percentage' => $classes > 0 ? ($coveredClasses / $classes) * 100 : 0
            ],
            'element' => [
                'total' => $elements,
                'covered' => $coveredElements,
                'percentage' => $elements > 0 ? ($coveredElements / $elements) * 100 : 0
            ]
        ];
    } catch (Exception $e) {
        echo COLOR_RED . "Error parsing coverage report: " . $e->getMessage() . "\n" . COLOR_RESET;
        return null;
    }
}

/**
 * Display coverage results in a formatted table
 * 
 * @param array $coverage Coverage metrics
 */
function displayCoverageResults(array $coverage): void
{
    echo "Coverage Results:\n";
    echo "─────────────────────────────────────────────────\n";
    
    $metrics = [
        ['name' => 'Lines', 'key' => 'line', 'threshold' => MIN_LINE_COVERAGE],
        ['name' => 'Methods', 'key' => 'method', 'threshold' => MIN_METHOD_COVERAGE],
        ['name' => 'Classes', 'key' => 'class', 'threshold' => MIN_CLASS_COVERAGE],
    ];

    foreach ($metrics as $metric) {
        $data = $coverage[$metric['key']];
        $percentage = $data['percentage'];
        $passed = $percentage >= $metric['threshold'];
        
        $statusIcon = $passed ? COLOR_GREEN . '✓' : COLOR_RED . '✗';
        $statusColor = $passed ? COLOR_GREEN : COLOR_RED;
        
        printf(
            "%s %-10s: %s%6.2f%%%s (% 4d / % 4d) [Threshold: %.0f%%]\n",
            $statusIcon . COLOR_RESET,
            $metric['name'],
            $statusColor,
            $percentage,
            COLOR_RESET,
            $data['covered'],
            $data['total'],
            $metric['threshold']
        );
    }
    
    // Display elements for information
    $elemData = $coverage['element'];
    printf(
        "%s %-10s: %6.2f%% (% 4d / % 4d)\n",
        COLOR_BLUE . 'ℹ',
        'Elements' . COLOR_RESET,
        $elemData['percentage'],
        $elemData['covered'],
        $elemData['total']
    );
}

/**
 * Check if coverage meets all thresholds
 * 
 * @param array $coverage Coverage metrics
 * @return bool True if all thresholds are met
 */
function checkThresholds(array $coverage): bool
{
    $checks = [
        'line' => MIN_LINE_COVERAGE,
        'method' => MIN_METHOD_COVERAGE,
        'class' => MIN_CLASS_COVERAGE,
    ];

    foreach ($checks as $type => $threshold) {
        if ($coverage[$type]['percentage'] < $threshold) {
            return false;
        }
    }

    return true;
}

// Execute main function
exit(main());













